### ISSUE TITLE
Windows compatiblity

### ISSUE THREAD

**Issue by TheGuardianWolf** [restqa/cucumber-export#12]
When I created the teams connector, I was surprised that this did not run on Windows.

I couldn't figure out why this line was used, but it locks it to be run on Linux only

```
const logFileName = fs.readlinkSync('/proc/self/fd/' + this.stream.fd)
```

It seems that you are trying to get the log name passed in as an argument, couldn't this be done through `process.argv` for cross platform compatiblity?

Alternatively, it seems there is access to the stream object via the passed in options that is the file itself, but when I tried writing to it, the stream was closed. Perhaps it can be re-opened.

**Comment by olivierodo** [comment]
Hello,
Thanks, you are right, i didn't pay much attention on that part, this is definitely a critical path in order to get this module cross platform compatible.

**Comment by TheGuardianWolf** [comment]
I can make a pull request next time I have some spare time, in the meantime, do you have any additional knowledge about that options object passed in through cucumber? I went looking for docs and I couldn't find anything too helpful

**Comment by olivierodo** [comment]
Thanks appreciate a lot

**Comment by olivierodo** [comment]
> in the meantime, do you have any additional knowledge about that options object passed in through cucumber? I went looking for docs and I couldn't find anything too helpful

Sadly there is no such a documentation, i had to spend a lot of time to log each steps to understand what are the property available of the `options` object
This is where it starts :  https://github.com/cucumber/cucumber-js/blob/6.x/src/cli/index.js#L43
and how it's getting assign to the formatter : https://github.com/cucumber/cucumber-js/blob/6.x/src/formatter/index.js

**Comment by TheGuardianWolf** [comment]
I've managed to get the stream object/log object to work in linux but on Windows they are closed prematurely for some reason, will dig into this further.

So I have managed to eliminate the file descriptor usage thankfully, I just want to avoid opening up another fs stream via arguments parsing and try to use cucumber provided stuff first.

**Comment by TheGuardianWolf** [comment]
Left #15 , it's the best I can do given this particular module is async and cucumber uses non async formatters mostly

**Comment by olivierodo** [comment]
Agree that definitely the key challenge of this module.
I merged your changes, so the behavior on windows is unstable ? 
Nothing we can do unless [cucumber](https://github.com/cucumber/cucumber-js) get improved to handle asynchronous formatter right ?

**Comment by TheGuardianWolf** [comment]
The behaviour seems to be consistent, essentially it's the same implementation as what you did before but not using a file descriptor, it's just seems hacky
