### ISSUE TITLE
Rename the export 'http' to 'webhook'

### ISSUE THREAD

**Issue by olivierodo** [restqa/cucumber-export#19]
Currently one of the export is named 'http' which is in fact a webhook support.
In order to align with the common terms, let's rename the http export to webhook export.

**Comment by tony-go** [comment]
Hi 👋 

This is the file you mention?

https://github.com/restqa/cucumber-export/blob/master/src/reports/http.js

**Comment by olivierodo** [comment]
Mostly yes, it should be only renaming a few files.
And update the documentation.
