### ISSUE TITLE
Rename http-html-report to html-remote

### ISSUE THREAD

**Issue by olivierodo** [restqa/cucumber-export#77]
Hello 👋,

### 👀 Background 

The http-html-report supposed to be the current html report but hosted on a remote server.

### ✌️ What is the actual behavior? 

Everything is working well however the name `http-html-report` is confusing.

### 🕵️‍♀️ How to reproduce the current behavior? 

1. clone repository
2. install depends `npm i && npm run html-report:install`
3. build `npm run html-report:build`
4. enable the `http-html-report` in the example
add the following property at this position on the file https://github.com/restqa/cucumber-export/blob/master/example/formatter.js#L18
```
...
    {
      type: 'http-html-report',
      enabled: true,
      config: {
        url: 'https://dashboard.restqa.io/reports'
      }
    },
...
```
5. run the command `npm run example:success`
6. You will see the http-remote-report results and click on the link to access to the report 
screenshot:
<img width="1306" alt="Screen Shot 2564-09-04 at 16 31 45" src="https://user-images.githubusercontent.com/4768226/132107341-8c466801-d84c-4a08-9c97-fc0413b1b350.png">

> The html report is stored on the server with a limit of time of 5 minutes.

###   🤞 What is the expected behavior?

Let's change the name of `http-html-report` to `html-remote`, its more friendly.

### 😎 Proposed solution to consider.

- [ ] Rename the reporter
- [ ] Update the documentation
- [ ] Update the example folder

Cheers.

**Comment by olivierodo** [comment]
After checking i realized that you might face issue on running the command `npm run example:success`.
Such as:
![image](https://user-images.githubusercontent.com/4768226/132107442-bf6e22b2-a26e-42a7-89c1-2a1bf94ddfa0.png)

The issue is coming from the fact the current example report is containing an image attached, and then the remote server is not accepting such a big payload...
So for the time being i would propose to disable the attachment.of the image.
Then You will just need to comment the lines:
https://github.com/restqa/cucumber-export/blob/master/example/features/setup.js#L27

**Comment by morgan557** [comment]
helllo, i think i'm gonna fix this issue.
